# 注意：配置文件必须是bootstrap.properties或者bootstrap.yml，如果配置application.properties或者application.yml会导致加载不到配置
server:
  port: 1300
spring:
  #  profiles:
  #    active: dev
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848 #指定配置中心地址
        file-extension: yaml #指定nacos配置中心的文件扩展名，默认为properties。支持：TEXT JSON XML YAML HTML Properties
    sentinel:
      transport:
        dashboard: localhost:8080 #配置sentinel控制地址
# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  #  mapper-locations: classpath:/com/ssy/distributed/lock/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #  typeAliasesPackage: com.ssy.distributed.lock.model
  global-config:
    db-config:
      logic-delete-field: valid
      logic-not-delete-value: 1
      logic-delete-value: 0
  #    #刷新mapper 调试神器
  #    db-config:
  #      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  #      id-type: UUID
  #      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  #      field-strategy: 2
  #      #驼峰下划线转换
  #      column-underline: false
  #      #数据库大写下划线转换
  #      #      capital-mode: true
  #      #逻辑删除配置
  #      logic-delete-value: 1
  #      logic-not-delete-value: 0
  #    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql
feign:
  client:
    config:
      default:
        connect-timeout: 60000 #请求连接的超时时间，默认时间为1秒
        read-timeout: 30000 #请求处理的超时时间
  sentinel:
    enabled: true #开启sentinel对Feign的支持
